strukturag/nextcloud-spreed-signaling

server.conf.in, src/signaling/backend_server.go, src/signaling/hub.go, src/signaling/mcu_common.go, src/signaling/mcu_janus.go, src/signaling/mcu_test.go
Can be used to query number of sessions, rooms and (if Janus is configured), overall MCU clients and publishers.
=> Add basic stats API.

.dockerignore, Dockerfile, README.md, docker-compose.yml, docker/coturn/Dockerfile, docker/janus/Dockerfile
~~Still a work in progress.~~ Now complete.
This is the configuration I am using on my own server with some extra Janus command line flags and a separate Coturn server. I've made several calls with it and it works.
=> Add Docker resources

src/signaling/api_signaling.go, src/signaling/backend_server.go, src/signaling/backend_server_test.go, src/signaling/testclient_test.go
This is required so clients can differentiate between no longer being invited or the room being deleted. Fixes #25.
cc @nickvergessen
=> Add "reason" field to disinvite message.

dependencies.tsv, src/signaling/janus_client.go, src/signaling/mcu_janus.go
Janus no longer reports `nacks` since 0.7.3 but changed the field to `lost`.
Fixes #37 
CC @danxuliu
=> Update "janus-go" dependency to handle changed slowlink message.

.gitignore, Makefile, README.md, dependencies.tsv, proxy.conf.in, server.conf.in, src/proxy/main.go, src/proxy/proxy_client.go, src/proxy/proxy_server.go, src/proxy/proxy_session.go, src/server/main.go, src/signaling/api_proxy.go, src/signaling/api_signaling.go, src/signaling/client.go, src/signaling/clientsession.go, src/signaling/hub.go, src/signaling/mcu_common.go, src/signaling/mcu_janus.go, src/signaling/mcu_proxy.go, src/signaling/mcu_proxy_test.go, src/signaling/mcu_test.go
This is required for scaling out Nextcloud Talk for lots of users. Each publisher gets one of the proxy backends assigned based on load, all subscribers of this publisher will connect to the same backend. Different publishers in the same room can end up on different backends.
I'll add this PR to gather feedback from users. Please test this setup in your environment and provide feedback if you find problems.
CC @nickvergessen @danxuliu @ivansss
=> Support connecting to multiple Janus servers

src/signaling/mcu_janus.go
This fixes an issue where re-joining a room after error stopped the internal processing of deferred functions.
@danxuliu please take a look to see if this fixes the issue you were having.
=> Move processing of deferred method to dedicated DeferredExecutor.

src/signaling/mcu_janus.go
Reverts strukturag/nextcloud-spreed-signaling#15
Causes the MCU candidates sometimes to be sent before the offer / answer, resulting in errors on the client during processing.
=> Revert "Move processing of deferred method to dedicated DeferredExecutor."

src/signaling/backend_configuration.go, src/signaling/backend_configuration_test.go
Follow-up on #52 
- Always load backends in the order they are configured.
- Don't allow reload with old-style backend configurations.
- Update reload tests.
- Log what backends are added/changed/removed on reload.
cc @membero @jkahrs
=> Minor reload improvements

src/signaling/clientsession.go, src/signaling/hub.go
This helps with clients disconnecting / resuming while MCU responses
are being sent to them. With the change, the messages are stored in
the session and sent out when clients resume their session.
=> Send MCU messages through the session.

docker-compose.yml
The signaling server warns about the missing '--full-trickle' parameter, therefore adding this.
=> Add '--full-trickle' to janus command

src/proxy/proxy_session.go, src/signaling/mcu_janus.go
It could happen that objects were kept in maps (e.g. on the proxy server) if they reconnected to the WebRTC gateway during their lifetime. This resulted in incorrect load calculations.
=> Fix proxy client cleanup

src/signaling/api_signaling.go, src/signaling/backend_configuration.go, src/signaling/backend_configuration_test.go, src/signaling/clientsession.go
Otherwise urls like "https://server:443/foo/" will fail to find entries for "https://server/foo/" and vice versa.
=> Canonicalize all URLs before comparisons / lookups.

src/client/main.go
Fixes #70 
The signaling backend expects the auth backend to reply with an OCS compliant structure. The provided client did not reply with such as response and triggered an `Incomplete OCS response` error in the signaling backend.
=> Make the response from the client auth backend OCS compliant

src/proxy/proxy_server.go, src/proxy/proxy_session.go, src/signaling/hub.go, src/signaling/mcu_janus.go, src/signaling/mcu_proxy.go
This is required on some architectures as per https://golang.org/pkg/sync/atomic/#pkg-note-BUG
Fixes #71
=> Align 64-bit members that are accessed atomically.

Makefile
Fixes recent CI build problems.
=> make: Only build "godeps" binary once.

src/signaling/mcu_janus.go
Removes warning in Janus:
```
[WARN] Subscriber is using the legacy 'listener' ptype
```
=> Stop using legacy ptype "listener".

api_proxy.go, backend_configuration.go, clientsession.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, mcu_test.go, proxy/proxy_server.go, server.conf.in
- Individually for each backend.
- For the proxy client (i.e. signaling server using cluster of proxies).
- For the proxy server / MCU.
The smallest bandwidth configured will be used, e.g. if a backend has a
larger limit than the MCU assigned for the stream, the limit of the MCU
server will be used.
=> Support defining maximum bandwidths at diferent levels.

README.md
Without the trailing slash, the config will not work. Instead the Nextcloud talk client will receive an error 400.
See also https://help.nextcloud.com/t/error-400-when-trying-to-access-high-performance-backend-signaling/106999/2
=> fix(docs): update config example for Apache proxy config

README.md
There is a small but significant error in the Caddy v2 example configuration. The reverse proxy directive applies to the new path not to the old path hence you need to also strip the prefix from the reverse proxy directive in order for it to work.
=> [Fix][Documentation] Fix Caddy v2 Example Config

mcu_janus.go, notifier.go, notifier_test.go, proxy.conf.in, proxy/main.go, proxy/proxy_server.go, server/main.go
Assume one Janus server is only used by one signaling server / -proxy.
With that, we can notify publisher events locally instead of through NATS and can remove code that looks up publisher rooms by their ids on Janus.
=> Remove NATS notifications for Janus publishers

client.go, clientsession.go, hub.go, hub_test.go, natsclient_loopback.go, room.go, virtualsession.go
This helps in detecting clients that disconnect while a backend request for them is still active (e.g. joining a room).
=> Make client message processing asynchronous.

Makefile
Otherwise it fails like
```
GOPATH="/go/src/github.com/strukturag/nextcloud-spreed-signaling/vendor:/go/src/github.com/strukturag/nextcloud-spreed-signaling" /usr/local/go/bin/go get -u github.com/mailru/easyjson/...
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/josharian/intern v1.0.0
PATH=/usr/local/go/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GOPATH="/go/src/github.com/strukturag/nextcloud-spreed-signaling/vendor:/go/src/github.com/strukturag/nextcloud-spreed-signaling" ./vendor/bin/easyjson -all api_signaling.go
/bin/sh: 1: ./vendor/bin/easyjson: not found
```
=> adjust easyjson for multiarch builds

backend_client_test.go, backend_configuration.go, backend_configuration_test.go, backend_server_test.go, hub_test.go
Prevents clients from sending a HTTP auth URL to trigger an insecure connection from the signaling server to Nextcloud.
@LukasReschke FYI
Fixes #130
=> Force HTTPS for backend connections in old-style configurations.

geoip.go, geoip_test.go, mcu_proxy.go, mcu_proxy_test.go, server.conf.in
This can be used for example to route all users on continent A to proxies on continent B. Useful if no proxy exists on continent A and the global selection chooses a non-ideal proxy.
=> Support continent mapping overrides.

api_proxy.go, clientsession.go, hub.go, hub_test.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, mcu_test.go, mock_data_test.go, proxy/proxy_server.go, testclient_test.go
Follow-up to #157 to support individual permissions when a session is changed.
E.g. if a client publishes audio/video and no longer has the video permission, the whole publisher will be closed. Previously this was only checking the generic "media" permission.
CC @nickvergessen
=> Check individual audio/video permissions on change.

api_signaling.go, hub.go, room.go, room_test.go
This helps with matching signaling sessions with sessions in Talk.
=> Include room session id in "joined" events.

api_signaling.go, clientsession.go, clientsession_test.go, mcu_test.go
This will still be capped to any backend / proxy / Janus limits.
=> Clients can provide the maximum publishing bandwidth in offer requests.

api_signaling.go, docs/standalone-signaling-api-v1.md, hub.go, room.go, session.go, testclient_test.go, transient_data.go, transient_data_test.go
Transient room data only exists while sessions are connected to a room, i.e. it is not stored persistently in a database. Changes are broadcast to all sessions in the room and the initial state is sent to new sessions on join.
A new feature flag was added so clients can check if transient data is available and sessions need a new permission to be able to set / change / remove transient data fields.
This could be used to store data that is valid while a meeting is taking place but can be cleared when nobody is connected.
=> Add API for transient room data.

api_signaling.go, clientsession.go, hub.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, proxy/proxy_session.go
Although related, this is independent from #191.
Tested also when running against a proxy :-)
When a publisher has a connection the publisher can update the connection (for example, to add a video track to an audio only connection) by sending an updated offer to Janus. Janus detects that, adjusts the connection and then sends back an answer. Once the publisher connection is updated Janus starts a renegotiation for the subscribers and generates the offers to be sent to them.
The signaling server did not handle the event, so the offers were not sent and the subscriber connections were not updated. Now the offers are sent as needed, which makes possible for the renegotiation to be completed by the clients.
In this case the `offer` message will also include an `update` parameter so clients …
=> Send updated offers to subscribers after publisher renegotiations

mcu_proxy.go, server.conf.in
If the hostname of a proxy server resolves to multiple IP addresses, a connection is established to each of them.
Changes to the DNS are monitored regularly and proxy connections are created or deleted as necessary.
=> Support DNS discovery for proxy server URLs.

clientsession.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, mcu_test.go
Follow up to #195
[When the permissions are updated and the session is no longer allowed to publish audio or video the publisher is closed](https://github.com/strukturag/nextcloud-spreed-signaling/blob/8fd9c688b6bdfe6f92259b07e1c4004fd432c637/clientsession.go#L970). The check is based on the [`mediaTypes` of the publisher](https://github.com/strukturag/nextcloud-spreed-signaling/blob/8fd9c688b6bdfe6f92259b07e1c4004fd432c637/mcu_janus.go#L883), which [are set when the publisher is initially created](https://github.com/strukturag/nextcloud-spreed-signaling/blob/8fd9c688b6bdfe6f92259b07e1c4004fd432c637/clientsession.go#L879) based on [the received offer](https://github.com/strukturag/nextcloud-spreed-signaling/blob/8fd9c688b6bdfe6f92259b07e1c4004fd432c637/clientsession.go#L854).
However, …
=> Fix mediaType not updated after publisher renegotiations

api_proxy.go, api_signaling.go, clientsession.go, hub.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, mcu_test.go, proxy/proxy_server.go, proxy/proxy_session.go
Follow up to #195
The WebUI of Talk sends a `sid` parameter in all the messages for an RTCPeerConnection to identify it (this has been there since the beginning, as it was implemented by SimpleWebRTC). Although that message is accepted by the mobile apps and the standalone signaling server they do nothing with it; they did not generate their own `sid` when needed (when they started the connection), and the messages sent by them did not contain the `sid` parameter either.
This pull request adds the `sid` parameter to the signaling server messages. The `sid` is set by the clients for publishers and by the signaling server for subscribers. Note that the `sid` is not propagated from publishers to subscribers, as they are different connections; the signaling server sets the `sid` for a …
=> Add specific id for connections and replace "update" parameter with it

api_signaling.go, clientsession.go, hub_test.go, session.go, testclient_test.go, transient_data_test.go
By default, the "join" events contain the whole userdata as received
from the "auth" response. This might include a "displayname" field
containing the display name of the associated user.
For privacy reasons in certain scenarios, some attendees should not
be able to know which other users are connected to a room, therefore
the "displayname" should be hidden for them. By default, no filtering
occurrs.
=> Add "permission" for sessions that may not receive display names.

hub.go
Follow up to #99 
Although the [server stats were registered](https://github.com/strukturag/nextcloud-spreed-signaling/blob/614c5f6e21ac59775b063454341f05033d259284/server/main.go#L144) `signaling_server_messages_total` was not incremented.
I have added the increment in `processMessage` in _hub.go_ (and only for successful messages), but I do not know if it is the right place, so please adjust it if needed :-) Thanks!
=> Fix "signaling_server_messages_total" stat not being incremented

hub.go, mcu_janus.go
Follow-up to #191 
The command `selectStream` also supports optional boolean flags `audio` and `video` that can be used to enable/disable receiving the corresponding media from the stream. The parameters of `selectStream` can also be included in the payload of `requestoffer` for example to subscribe a stream with video initially disabled.
The new flags are similar to the existing `substream` / `temporal`.
@danxuliu please review, is this something you could work with?
=> Support toggling audio/video in subscribed streams.

dist/init/systemd/sysusers.d/signaling.conf
The systemd unit makes use of the user "signaling", but it is not created in any way, so the directive is ignored.
By creating a sysusers file it is possible to tell the system to create a "signaling" user so that the directive is honoured.
For more information, see the sysusers.d manpage, at https://www.freedesktop.org/software/systemd/man/sysusers.d.html
This is mainly useful on systems running systemd, but the sysusers concept is implemented also by other projects that don't use systemd, like opensysusers, originated from Artix Linux.
=> dist: add systemd sysusers file

api_proxy.go, api_signaling.go, api_signaling_test.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go, proxy/proxy_server.go, testclient_test.go
This can be used to detect server features before performing the actual "hello" handshake.
Implements #273
=> Send initial "welcome" message when clients connect.

clientsession.go, grpc_common.go, grpc_common_test.go, grpc_server_test.go
=> Fix issues on slow CPUs

backend_storage_etcd.go, etcd_client.go, etcd_client_test.go, grpc_client.go, mcu_proxy.go
It could happen that the initialized event was triggered even though the watch was not fully created yet.
=> etcd: Fix race in initialized event.

backend_server.go, grpc_client.go, grpc_server.go, grpc_sessions.proto, hub.go, hub_test.go, roomsessions.go, roomsessions_builtin.go
Previously there was a difference in the events being received by other sessions for the clustered case compared to the single-server case. Now the events / ordering are the same for both cases.
=> Disconnect sessions with the same room session id synchronously.

.github/workflows/tarball.yml, Makefile, go.mod, vendor_helper_test.go
@dzatoah / @sunweaver would this help with the dependencies from #279?
=> make: Include vendored dependencies in tarball.

api_backend.go, api_proxy.go, api_signaling.go, api_signaling_test.go, capabilities.go, capabilities_test.go, client/main.go, clientsession_test.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go, proxy/proxy_server.go, room_ping.go, testclient_test.go
Implements the signaling server part of https://github.com/nextcloud/spreed/issues/7336
cc @nickvergessen
=> Support hello auth version "2.0" with JWT

Dockerfile
`apt` does not have a stable CLI interface
=> Switch to apt-get on CLI

dist/init/systemd/signaling.service
Introduced in https://github.com/strukturag/nextcloud-spreed-signaling/pull/276.
* https://gitlab.com/packaging/nextcloud-spreed-signaling/-/commit/3fcaf45b6f32276ad1c42d0ff6a337db4d66da79#note_1055183029
* https://github.com/nextcloud/vm/issues/2371
* https://github.com/strukturag/nextcloud-spreed-signaling/issues/315
As @Tachi107 left a comment about `ProcSubset`, i tested the other way around and leave ´@resources` in place while removing `ProcSubset=pid`, still does not work.
=> remove @resources from SystemCallFilter

syscallconn.go
Fixes error with newer versions of golangci-lint.
=> Explicitly use type "sysConn".

docker/README.md
The parameter should be `BACKEND_<NAME>_SHARED_SECRET` and not `BACKEND_<NAME>_SECRET`.
=> Fix example in docker README

docker/server/entrypoint.sh
the docker environment variables TURN_API_KEY and TURN_SECRET didn't work this is because the entrypoint.sh is only replacing the values but do not uncomment the line like the other replacements do
=> TURN_API_KEY and TURN_SECRET fix

docker/README.md, docker/server/entrypoint.sh
To allow using the official docker image of the signaling server for development as well, it would be nice to add `SKIP_VERIFY` as an environment option as well. 
If this was purposely not added, because it's considered a development option, feel free to just close this.
=> Allow SKIP_VERIFY in docker image

docker/server/entrypoint.sh
Replaces #432
@3x3cut0r Please test, this is better than your change as it won't replace other `secret`  values in the config files.
=> docker: Don't rely on default values when updating TURN settings.

.github/workflows/tarball.yml, Makefile, go.mod, go.sum, tools.go
Instead of manually copying files to vendor folder, try to get "go" to detect dependencies instead.
=> Simplify vendoring.

docker/README.md, docker/server/entrypoint.sh, server.conf.in
For easier work in a development environment (e.g. https://github.com/juliushaertl/nextcloud-docker-dev) it would be nice if we could set the `allowall` property directly in the docker image.
=> Add allowall to docker image

clientsession.go
Found in https://github.com/strukturag/nextcloud-spreed-signaling/actions/runs/5276816848/jobs/9544227428?pr=491
=> Add missing lock for "roomSessionId" to avoid potential races.

.github/workflows/tarball.yml, .github/workflows/test.yml, README.md, go.mod
This removes support for Go 1.18
=> Follow the Go release policy by supporting only the last two versions.

backend_storage_static.go
=> Log warning if no (static) backends have been configured.

backend_configuration_test.go, backend_storage_static.go, server.conf.in
Only applies to static backend configuration.
Resolves #337
=> Fallback to common shared secret if none is set for backends.

api_signaling.go, backend_server_test.go, docs/standalone-signaling-api-v1.md, hub.go, room.go, testclient_test.go, transient_data.go, transient_data_test.go
=> Support TTL for transient data.

.github/workflows/tarball.yml, .github/workflows/test.yml, README.md, go.mod
This follows the Go release policy of only supporting the last two versions.
=> No longer support Golang 1.19.

config.go, config_test.go, hub.go, mcu_proxy.go, proxy/proxy_tokens_static.go
=> Skip options from default section when parsing "geoip-overrides".

dns_monitor.go, dns_monitor_test.go
Problem happened in CI tests of GrpcClients which tried to remove the entry concurrently with `onLookup`.
When trying to remove the entry here:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c85b31bd2437419fd1df1f2e3f870a213fd06c06/grpc_client.go#L755
The lock was acquired here:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c85b31bd2437419fd1df1f2e3f870a213fd06c06/grpc_client.go#L744
Concurrently, the DNS monitor was notifying about the lookup here:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c85b31bd2437419fd1df1f2e3f870a213fd06c06/grpc_client.go#L511
And previously acquired its lock here:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c85b31bd2437419fd1df1f2e3f870a213fd06c06/dns_monitor.go#L64
Found here: …
=> Fix deadlock when entry is removed while receiver holds lock in lookup.

docs/prometheus-metrics.md, http_client_pool.go, http_client_pool_stats_prometheus.go
Fixes #666 
@nickvergessen This is something you could add to your monitoring once released.
=> Add metrics for current number of HTTP client connections.

proxy_config_static_test.go
Problem was caused by the initial wakeup check sometimes running, clearing the expected events too soon.
=> Fix flaky "TestProxyConfigStaticDNS".

.github/workflows/check-continentmap.yml, continentmap.go, scripts/get_continent_map.py
Now fetching from https://github.com/datasets/country-codes repository.
=> Update source of continentmap to original CSV file.

.github/workflows/lint.yml
This should prevent things like #686 from landing which bumped the required version of Go to 1.21 while we still support 1.20.
=> CI: Check dependencies for minimum supported version.

backend_storage_etcd.go, backend_storage_etcd_test.go, etcd_client.go, etcd_client_test.go, go.mod, grpc_client.go, proxy_config_etcd.go
- Properly cancel watch if object is closed.
- Retry watch if interupted.
- Pass revision to watch to not miss changes.
=> Update etcd watch handling.

mcu_janus.go
While Janus 1.x still supports backwards compatible APIs, it would be better to switch to new APIs.
=> Improve support for Janus 1.x

clientsession.go, hub.go, roomsessions_test.go, session.go, virtualsession.go
Reduces memory size per session and make hub lock usage consistent.
=> Don't keep expiration timestamp in each session.

api_signaling.go, hub_test.go
Allow empty `roomType` values.
Tentative fix for https://github.com/nextcloud/spreed/issues/12252 (cc @danxuliu).
=> Relax "MessageClientMessageData" validation.

grpc_server.go
=> grpc: Replace environment variables in listening address.

.github/workflows/tarball.yml, Makefile, docker/proxy/Dockerfile, docker/server/Dockerfile
This makes sure the go.mod / go.sum files are not updated when generating the "vendor" folder (which will generate common files and thus might update the CLI tools). Mismatching "vendor" and "go.*" files will break building.
=> make: Don't update CLI tools before installing.

capabilities.go, capabilities_test.go
Simply using the values from the "Cache-Control" header is problematic as recent setups of Nextcloud are not setting the header and capabilities would not be cached at all in these cases.
Follow-up to #780 
@SystemKeeper PTAL
=> Enforce a minimum duration to cache capabilities.

backend_configuration_stats_prometheus.go, backend_storage_etcd.go, backend_storage_static.go, docs/prometheus-metrics.md
Resolves #787 
@pmarini-nc FYI, don't know if you have the possibility to test this from source
=> Expose backend session limits through prometheus stats.

api_signaling.go, api_signaling_easyjson.go, capabilities.go, client.go, clientsession.go, docs/standalone-signaling-api-v1.md, federation.go, federation_test.go, go.mod, hub.go, hub_test.go, room.go, server.conf.in, testclient_test.go
Needs https://github.com/nextcloud/spreed/pull/12604
=> Federation support

api_backend.go, clientsession.go, federation.go, federation_test.go, hub.go, hub_test.go, room.go, room_ping.go, room_ping_test.go, roomsessions_test.go, session.go, testclient_test.go, virtualsession.go
Fixes https://github.com/nextcloud/spreed/issues/12917
cc @nickvergessen
=> Send ping requests to local instance for federated sessions.

capabilities.go, capabilities_test.go
If capabilities are expired and requested from multiple clients concurrently, this could cause concurrent (duplicate) requests to the same Nextcloud host. With this change, only a single request is sent to Nextcloud in such cases.
Fixes #832 
@nickvergessen FYI
=> Don't update capabilities concurrently from same host.

api_async_easyjson.go, api_proxy.go, api_proxy_easyjson.go, api_signaling.go, api_signaling_easyjson.go, clientsession.go, clientsession_test.go, mcu_common.go, mcu_janus.go, mcu_janus_publisher.go, mcu_janus_remote_publisher.go, mcu_janus_remote_subscriber.go, mcu_janus_subscriber.go, mcu_proxy.go, mcu_proxy_test.go, mcu_test.go, proxy/proxy_server.go, proxy/proxy_server_test.go
=> Support passing codec parameters when creating publishers.

docker/docker-compose.yml
- Remove deprecated `version` param
- Upgrade `nats` to latest stable (personally, I've always upgraded it on my deployement without any issues for 3y)
- Stick `coturn` to latest stable instead of `latest`
=> docker: apply Docker image versioning

Makefile
Should fix problems where a new version gets installed causing changes to unaffected (generated) files.
=> make: Pin version of "google.golang.org/protobuf/cmd/protoc-gen-go".

capabilities.go, go.mod, go.sum
The previously used code was unmaintained for a very long time and caused problems for packagers.
Fixes #914
=> Migrate cache-control parsing to https://github.com/pquerna/cachecontrol

async_events_test.go, backend_server_test.go, hub_test.go, natsclient.go, natsclient_test.go
If the NATS server is offline for too long, the client will stay disconnected otherwise.
=> nats: Reconnect client indefinitely.

.gitignore, Makefile
=> Explicitly set TMPDIR to ensure that it is a path where go-installed utils (pe. easyjson-bootstrap) can be executed

dist/init/systemd/signaling.service
Fixes "Permission denied" errors on Fedora / RedHat systems.
Resolves #943
=> Add "/usr/lib64" to systemd ExecPath

mcu_janus_subscriber.go
This makes sure the subscriber is not cached but created newly which will fetch the publisher room id again in case it was changed since the initial subscription.
Fixes #958
CC @danxuliu
=> Close subscribers on errors during initial connection.

client/main.go, proxy/main.go, server/main.go
Currently, I cannot override GOMAXPROCS, because it is hardcoded to be as much as CPUs number.
Since Go 1.5 the default value already set as number of CPUs => previous logic applies by default.
Patch allows to set/override default behavior via environment variable.
https://stackoverflow.com/questions/17853831/what-is-the-gomaxprocs-default-value
https://pkg.go.dev/runtime#GOMAXPROCS
=> Allow to set GOMAXPROCS

mcu_janus.go, mcu_proxy.go, proxy/proxy_remote.go
This prevents all servers from reconnecting at the same time in case of network interruptions or service restarts.
=> Add jitter to reconnect intervals.

.golangci.yml
Using "synctest.Wait" is fine as we set GOEXPERIMENT=synctest when running affected code.
=> CI: Disable "stdversion" check of govet.
