strukturag/nextcloud-spreed-signaling

README.md, scripts/get-version.sh, scripts/get_continent_map.py
Several small changes in build/installation procedure. Original goal was to let run it on [Free]BSD, but in general is makes the scripts' run more flexible across Unix like and Linux distros.
=> FreeBSD updates

src/signaling/api_signaling.go, src/signaling/hub.go, src/signaling/janus_client.go, src/signaling/mcu_janus.go
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos in comments and error messages (found by codespell)

Makefile, src/signaling/backend_server_test.go, src/signaling/hub_test.go
Some of the CI runs randomly fail. This PR attempts to fix them
=> Fix flaky CI test runs

server.conf.in, src/signaling/api_backend.go, src/signaling/api_signaling.go, src/signaling/api_signaling_test.go, src/signaling/backend_client.go, src/signaling/backend_client_test.go, src/signaling/backend_configuration.go, src/signaling/backend_configuration_test.go, src/signaling/backend_server.go, src/signaling/backend_server_test.go, src/signaling/clientsession.go, src/signaling/hub.go, src/signaling/hub_test.go, src/signaling/natsclient.go, src/signaling/room.go, src/signaling/room_test.go, src/signaling/roomsessions_test.go, src/signaling/session.go, src/signaling/testclient_test.go
Work in progress, needs some tests to make sure the isolation works.
=> Add support for multiple Nextcloud backends

src/signaling/client.go, src/signaling/clientsession.go
Already happens in per-client/-session goroutines, so won't block others.
=> Process NATS messages directly without passing to separate channel in client.

server.conf.in, src/server/main.go, src/signaling/api_proxy.go, src/signaling/mcu_proxy.go
This is useful if multiple signaling servers share the same list of proxy servers.
=> Add support for fetching proxy URLs from etcd cluster.

src/signaling/backend_client.go, src/signaling/backend_configuration.go, src/signaling/backend_configuration_test.go, src/signaling/hub.go
- Reload Backend Configuration without destroying unchanged backends
- Only used when configured with backends parameter
=> Feature: Reload Backends on SIGHUP

README.md
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> README: Add missing information for creating group

src/signaling/client.go, src/signaling/mcu_proxy.go
Fixes issue where broken connections to the proxies sometimes were not detected properly.
=> Send ping to proxy regularly to detect broken connection.

Makefile
Trying to build with different `GOARCH` (due to https://github.com/nextcloud/vm/issues/1728) leads to errors with current build:
```
/bin/sh: 1: ./vendor/bin/godeps: not found
```
=> adjust godeps for multiarch builds

.github/workflows/test.yml, Makefile
=> Update make targets to support parallel building.

notifier.go, notifier_test.go
=> Support multiple waiters for the same key.

backend_client.go, hub_test.go
Implements #117 
CC @nickvergessen
=> Fetch capabilities to check if "v3" signaling API of Talk should be used.

hub.go, testclient_test.go, virtualsession_test.go
This is necessary so the participant list can show correct icons (e.g. talking/muted).
=> Notify new clients about flags of virtual sessions

backend_client.go, backend_client_test.go
=> Only include body in 307/308 redirects if going to same host.

hub.go, hub_test.go, room.go, server.conf.in
Previously it was possible to subscribe any stream if the session id of the publisher was known.
=> Only allow subscribing if both users are in the same room and call.

api_backend.go, api_signaling.go, backend_server.go, docs/standalone-signaling-api-v1.md, hub.go, room.go, room_test.go, testclient_test.go
Implements #203
CC @nickvergessen
=> Add special events to update "incall" flags of all sessions.

.github/workflows/lint.yml, .github/workflows/test.yml, Makefile, README.md, go.mod, go.sum
Currently this is Go 1.17 and 1.18.
=> Only support last two versions of Golang (1.17 / 1.18).

.github/workflows/docker.yml, Dockerfile
Makes sure build environment in `Dockerfile` works and with that fixes #232.
=> CI: Build docker image.

mcu_janus.go
Requires #229
~~`requestOffer` messages can now include an `update` parameter to trigger an update of the current Janus connection rather than closing it and creating a new one.~~
~~The `offer` message will also include an `update` parameter if it was requested as such so clients can differentiate between offers to create new connections or update the existing one.~~
The `sid` parameter of `requestOffer` messages is now checked to update the current Janus connection when it matches the `sid` of the subscriber rather than closing it and creating a new one.
Updating a connection is needed for clients to renegotiate their received media without interrupting the current connection. For example, to stop receiving video by triggering a new offer from Janus and then setting the video transceiver …
=> Add support for request offers to update subscriber connections

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/test.yml
This helps checking action changes.
=> CI: Run when workflow yaml file has changed.

backend_server.go
Temporary workaround for #254.
FYI @nickvergessen @danxuliu
=> Increase allowed body size for backend requests.

.github/workflows/docker-coturn.yml, .github/workflows/docker-janus.yml
=> CI: Test building coturn/janus Docker images.

.github/workflows/command-rebase.yml
=> Add command bot for "/rebase".

docker/janus/Dockerfile
Running these without issues ATM.
=> Update Dockerfile versions

README.md
Can help building better code and detect some issues.
See https://goreportcard.com/report/github.com/strukturag/nextcloud-spreed-signaling
=> Add Go Report card

Dockerfile
See https://github.com/advisories/GHSA-h8c3-8522-vxc6
=> Update Alpine to 3.15 version, fix CVE-2022-28391

hub.go, hub_test.go, room.go, room_ping.go, room_ping_test.go
Requires https://github.com/nextcloud/spreed/pull/7338
Implements #246
=> Combine ping requests of different rooms on the same backend.

capabilities.go, capabilities_test.go, hub_test.go
=> Support arbitrary capabilities values.

hub.go, hub_test.go, mcu_test.go, testclient_test.go
Also update tests for "requestoffer" / "sendoffer".
=> Fix handling of "unshareScreen" messages and add test.

api_async.go, api_signaling.go, clientsession.go, hub.go, hub_test.go, room.go, testclient_test.go, virtualsession.go
Adding the tests showed a few issues with virtual sessions and clustered setups which have been fixed.
=> Add tests for virtual sessions.

.github/workflows/deploydocker.yml, .github/workflows/docker.yml, docker/proxy/Dockerfile, docker/server/Dockerfile
Signed-off-by: Zoey <zoey@z0ey.de>
Needed for https://github.com/nextcloud/all-in-one/pull/1583
=> add aarch64/arm64 docker build

client.go
This causes flaky races if "Wait" and "Add" are being used from different goroutines.
=> Stop using WaitGroup to detect finished message processing.

client.go, grpc_client_test.go, hub_test.go, room.go, session_test.go, testclient_test.go, testutils_test.go, virtualsession_test.go
=> Test: add timeout while waiting for etcd event.

api_backend.go, api_signaling.go, backend_server.go, docs/standalone-signaling-api-v1.md, hub_test.go, room.go, testclient_test.go
=> Implement "switchto" support

api_signaling.go, clientsession.go, clientsession_test.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go, room.go, testclient_test.go, virtualsession.go, virtualsession_test.go
=> Allow internal clients to set / change the "inCall" flags.

.github/workflows/docker-janus.yml, .github/workflows/docker.yml, docker/proxy/Dockerfile, docker/server/Dockerfile
=> Fix docker images.

docker/server/entrypoint.sh
=> Write backends comma-separated to config

clientsession.go, hub_test.go, testclient_test.go
Should help in fixing some flaky tests on GitHub CI.
=> Fix duplicate join events

docker/proxy/Dockerfile, docker/server/Dockerfile
This fixes flaky builds on GitHub CI.
=> docker: Don't build concurrently.

hub.go, hub_test.go
=> Use GeoIP overrides if no GeoIP database is configured.

api_signaling.go, clientsession.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go, roomsessions_builtin.go, roomsessions_test.go
Closes #543 
@SystemKeeper could you please check if this resolves the issue for you? See the changed API docs for further information on the response.
=> Return response if session tries to join room again.

api_async.go, api_backend.go, api_backend_test.go, api_signaling.go, backend_server.go, backend_server_test.go, clientsession.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go, room.go, testclient_test.go
See https://github.com/nextcloud/spreed/issues/10410 for the Talk side.
=> Implement message handler for dialout support.

docker/proxy/Dockerfile, docker/server/Dockerfile, scripts/get-version.sh
Resolves #601 
CC @SystemKeeper
=> Include "~docker" in version if built on Docker.

docker/janus/Dockerfile
=> docker: Update Janus from 0.11.8 to 0.14.1.

docker/proxy/Dockerfile, docker/proxy/entrypoint.sh, docker/proxy/stop.sh, docker/proxy/wait.sh, docker/server/Dockerfile, docker/server/entrypoint.sh
- Run main process with PID 1
- Gracefully stop / wait for proxy.
=> Docker improvements

certificate_reloader.go, certificate_reloader_test.go, file_watcher.go, file_watcher_test.go, go.mod, go.sum, grpc_common_test.go, grpc_server.go, grpc_server_test.go
Avoids regular checking through `stat` to see if a file has changed.
=> Use fsnotify to detect file changes

hub.go, hub_test.go, server/main.go
This will wait for all non-internal sessions to be removed / expired but stop accepting new connections.
=> Gracefully shut down signaling server on SIGUSR1.

client.go
=> Don't log read error after we closed the connection.

allowed_ips.go, allowed_ips_test.go, backend_server.go, backend_server_test.go, hub.go, hub_test.go, proxy.conf.in, proxy/proxy_server.go, server.conf.in
=> Make trusted proxies configurable and default to loopback / private IPs.

clientsession.go
Deadlock could happen between
```
1 @ 0x44038e 0x451898 0x45186f 0x46f325 0x489f3d 0xbb7b76 0xbb7b45 0xc1fe52 0xc190f7 0x473461
0x46f324	sync.runtime_SemacquireMutex+0x24							/usr/lib/go-1.21/src/runtime/sema.go:77
0x489f3c	sync.(*Mutex).lockSlow+0x15c								/usr/lib/go-1.21/src/sync/mutex.go:171
0xbb7b75	sync.(*Mutex).Lock+0x55									/usr/lib/go-1.21/src/sync/mutex.go:90
0xbb7b44	github.com/strukturag/nextcloud-spreed-signaling.(*ClientSession).RoomSessionId+0x24	/build/nextcloud-spreed-signaling-1.2.3/clientsession.go:157
0xc1fe51	github.com/strukturag/nextcloud-spreed-signaling.(*Room).publishActiveSessions+0x231	/build/nextcloud-spreed-signaling-1.2.3/room.go:925
0xc190f6	github.com/strukturag/nextcloud-spreed-signaling.(*Room).run+0x36 …
```
=> Fix lock order inversion when leaving room / publishing room sessions.

api_backend.go, api_signaling.go, api_signaling_test.go, backend_client.go, backend_client_test.go, backend_server.go, backend_server_test.go, capabilities.go, capabilities_test.go, client/main.go, clientsession.go, hub.go, hub_test.go, room.go, room_test.go, roomsessions_test.go, session.go, testclient_test.go, virtualsession.go, virtualsession_test.go
The slice is a pointer already.
=> Don't use unnecessary pointer to "json.RawMessage".

.github/workflows/shellcheck.yml, docker/proxy/entrypoint.sh, scripts/log-simplifier.sh
Add shellcheck to CI to catch similar errors in the future.
=> docker: Fix proxy entrypoint.

hub_test.go, throttle.go, throttle_test.go
Also addresses comments from #747.
@danxuliu FYI
=> Throttle /64 subnets for IPv6.

backend_server.go, geoip.go, hub.go, mcu_janus.go, mcu_proxy.go, proxy/proxy_server.go, server/main.go
Further reducing the need for full service restarts on configuration changes.
=> Support reloading more settings

throttle.go, throttle_test.go
=> Prevent overflows when calculating throttle delay.

hub.go, hub_test.go
=> Don't throttle valid but expired resume requests.

.github/workflows/generated.yml
This makes sure the CI workflows are triggered on the modified code.
=> CI: Push generated code from service account.

docker/README.md, docker/proxy/Dockerfile, docker/proxy/entrypoint.sh, docker/server/Dockerfile, docker/server/entrypoint.sh
@szaimen would this work for your scenario?
=> docker: Support adding CA certificates to system trust store.

Makefile
This should fix issues like #845 
@hanserasmus FYI
=> make: Improve dependency tracking.

api_signaling.go, clientsession.go, docs/standalone-signaling-api-v1.md, hub.go, hub_test.go
Resolves #822 
CC @SystemKeeper
=> Support recipient "call".

federation.go, federation_test.go, testclient_test.go
=> Include features of federated clients in "join" events.

api_backend.go, api_backend_easyjson.go, api_signaling.go, async_events_nats.go, backend_server.go, docs/standalone-signaling-api-v1.md, etcd_client.go, grpc_client.go, hub.go, mcu_common.go, mcu_janus.go, mcu_proxy.go, mcu_test.go, proxy/proxy_server.go, proxy/proxy_server_test.go
@nickvergessen please take a look if this contains all information you want to show in the admin UI.
=> Add serverinfo API

backend_client.go, backend_client_stats_prometheus.go, docs/prometheus-metrics.md
Resolves #968
@nickvergessen FYI
=> Add metrics for backend client requests.

mcu_common.go, mcu_janus_publisher.go, mcu_proxy.go, mcu_test.go, proxy/proxy_remote.go, proxy/proxy_server.go, proxy/proxy_server_test.go, proxy/proxy_session.go
Follow-up to #986 
@danxuliu FYI
=> Close subscriber if remote publisher was closed.

backend_client.go
=> Use backend id in backend client stats to match other stats.
